Repository ThePorgs/Exegol-docs, pull requests merged in 2023-12, with the labels that each got.

#39 Add: installation guideline for Windows Defender users
  source/getting-started/install.rst
Labels: resources

#38 Release 3.1.2 (images)
  source/assets/installed_tools/lists/ad_3.1.2_amd64.csv
  source/assets/installed_tools/lists/ad_3.1.2_arm64.csv
  source/assets/installed_tools/lists/full_3.1.2_amd64.csv
  source/assets/installed_tools/lists/full_3.1.2_arm64.csv
  source/assets/installed_tools/lists/light_3.1.2_amd64.csv
  source/assets/installed_tools/lists/light_3.1.2_arm64.csv
  source/assets/installed_tools/lists/osint_3.1.2_amd64.csv
  source/assets/installed_tools/lists/osint_3.1.2_arm64.csv
  source/assets/installed_tools/lists/web_3.1.2_amd64.csv
  source/assets/installed_tools/lists/web_3.1.2_arm64.csv
  source/assets/installed_tools/releases.csv
  source/community/contributors.rst
  source/community/maintainers.rst
  source/exegol-image/my-resources.rst
  source/exegol-image/services.rst
  source/getting-started/install.rst
  source/index.rst
  source/the-exegol-project/python-wrapper.rst
Labels: images

#41 Release 4.3.0 (wrapper)
  .github/workflows/automerger.yml
  source/assets/installed_tools/releases.csv
  source/exegol-image/my-resources.rst
  source/exegol-wrapper/advanced-uses.rst
  source/exegol-wrapper/install.rst
  source/exegol-wrapper/start.rst
  source/getting-started/install.rst
  source/the-exegol-project/python-wrapper.rst
Labels: wrapper
